on:
  reddit:
    url: https://www.reddit.com/r/FreeEBOOKS+freebooks
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message:  |
            ${{on.reddit.outputs.title}}
            ${{on.reddit.outputs.content}}
